# Generated by Django 4.2.7 on 2023-12-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_websitecategory_historyrecord_user_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
