# Generated by Django 4.2.7 on 2024-01-07 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
