# Generated by Django 4.2.7 on 2024-02-02 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_historyrecord_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyrecord',
            name='next_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_records', to='history.historyrecord'),
        ),
        migrations.AddField(
            model_name='historyrecord',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historyrecord',
            name='link',
            field=models.CharField(max_length=300),
        ),
    ]
