# Generated by Django 4.2.7 on 2023-12-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='category',
            new_name='categories',
        ),
    ]
