# Generated by Django 4.2.7 on 2023-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_rename_category_website_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='domain',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
