# Generated by Django 4.2.3 on 2024-02-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_alter_website_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('execption_name', models.CharField(max_length=100)),
                ('execption_text', models.TextField()),
            ],
        ),
    ]
