# Generated by Django 4.2.3 on 2024-02-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_unscraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='can_save',
            field=models.BooleanField(default=True),
        ),
    ]
